FROM      ltubuntu/ubuntu:14.04
MAINTAINER sunbin <sunbin945@163.com>

ENV JAVA_VERSION 7
ENV JDK_HOME /usr/lib/jvm/java-7-openjdk-amd64
#update
RUN  apt-get install -y  openjdk-7-jdk
# Install jdk
#RUN apt-get install -y install openjdk-${JAVA_VERSION}-jdk  && \
#    apt-get autoremove
